name: keystore_plugin
description: Flutter Plugin supporting key generation and signing with Android Keystore and iOS SecureEnclave keys.
version: 1.0.0
repository: https://github.com/b2cm/hidy_keystore_plugin

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  pointycastle: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.os_keystore_backend
        pluginClass: OsKeystoreBackendPlugin
      ios:
        pluginClass: OsKeystoreBackendPlugin
